### ISSUE TITLE
Add Movie Trailers

### ISSUE THREAD

**Issue by Maxiboy441** [Maxiboy441/schoolproject-3#125]
Add the movie trailer from the first concept.

**Comment by Maxiboy441** [comment]
Hey @mehrb98,
can you give me a status update about that feature? 

Thx

BTW: Please add estimations as well as start and end date (and book you times)

**Comment by feliperamoss** [comment]
![Image](https://github.com/user-attachments/assets/2355cfa0-0d64-4421-9afc-20d2d5e6b580)

**Comment by feliperamoss** [comment]
New image size
![Image](https://github.com/user-attachments/assets/09108516-6d76-46cd-b454-ee918fb97f29)
