### ISSUE TITLE
Package Research

### ISSUE THREAD

**Issue by Maxiboy441** [Maxiboy441/schoolproject-3#8]
Look which packages could be needed or helpfull, like one to automaticly make db migration from the model defenitions (Entity Framework (EF) ), etc. Find them, evaluate them and add them to the project (add also a link to them to the TC so other can research how to use them)

**Comment by feliperamoss** [comment]
I would recommend to use Entity Framework Core (EF Core) for database migrations, etc.

**Comment by Maxiboy441** [comment]
Nice Job, I would recommend ASP.NET Core Identity to add auth, as well as the Entity Framework Core (EF Core) to make database management more easy

**Comment by Maxiboy441** [comment]
@mehrb98 I would propose to decide which to use in a all discousion for the concept
