### ISSUE TITLE
Research docker vs bare metal

### ISSUE THREAD

**Issue by Maxiboy441** [Maxiboy441/schoolproject-3#9]
Research what it needs to deploy a C# Project via docker and if its worth todo vs bare metal on debian

**Comment by mehrb98** [comment]
Deploying C# Web Applications with Docker

**Prerequisites**

Install the following prerequisites:

 1)  [.NET 8+ SDK](https://dotnet.microsoft.com/download/dotnet/8.0)
 2) [Docker Community Edition](https://www.docker.com/products/docker-desktop)
